I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1491, in script
    w "Are you assuming I'm {i}old{/i}???"
Exception: Sayer 'w' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1491, in script
    w "Are you assuming I'm {i}old{/i}???"
  File "/Users/sam/renpy-8.0.3-sdk/renpy/ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/sam/renpy-8.0.3-sdk/renpy/ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'w' is not defined.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
Careful Watchers 1.0
Mon Oct 24 02:14:58 2022
